mkdir "Assets/Code",
mkdir "Assets/Databases",
mkdir "Assets/Editor",
mkdir "Assets/Resources",
mkdir "Assets/Resources/Animation",
mkdir "Assets/Resources/Audio",
mkdir "Assets/Resources/Audio/Sounds",
mkdir "Assets/Resources/Audio/Music",
mkdir "Assets/Resources/Fonts",
mkdir "Assets/Resources/Materials",
mkdir "Assets/Resources/Models",
mkdir "Assets/Resources/Prefabs",
mkdir "Assets/Resources/Prefabs/UI",
mkdir "Assets/Resources/RenderTextures",
mkdir "Assets/Resources/Scenarios",
mkdir "Assets/Resources/Scenes",
mkdir "Assets/Resources/Shaders",
mkdir "Assets/Resources/Skyboxes",
mkdir "Assets/Resources/Sprites",
mkdir "Assets/Resources/Sprites/Icons",
mkdir "Assets/Resources/Text",
mkdir "Assets/Resources/Textures",
mkdir "Assets/Resources/Third Party"
PAUSE